// Code generated by MockGen. DO NOT EDIT.
// Source: loyalty-service/internal/service (interfaces: BalanceRepo)
//
// Generated by this command:
//
//	mockgen -destination=mocks/balance_repo.go -package=mocks . BalanceRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "loyalty-service/internal/model"
	reflect "reflect"

	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockBalanceRepo is a mock of BalanceRepo interface.
type MockBalanceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceRepoMockRecorder
	isgomock struct{}
}

// MockBalanceRepoMockRecorder is the mock recorder for MockBalanceRepo.
type MockBalanceRepoMockRecorder struct {
	mock *MockBalanceRepo
}

// NewMockBalanceRepo creates a new mock instance.
func NewMockBalanceRepo(ctrl *gomock.Controller) *MockBalanceRepo {
	mock := &MockBalanceRepo{ctrl: ctrl}
	mock.recorder = &MockBalanceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceRepo) EXPECT() *MockBalanceRepoMockRecorder {
	return m.recorder
}

// FindWithdrawalsByUser mocks base method.
func (m *MockBalanceRepo) FindWithdrawalsByUser(ctx context.Context, userID int) ([]model.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithdrawalsByUser", ctx, userID)
	ret0, _ := ret[0].([]model.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWithdrawalsByUser indicates an expected call of FindWithdrawalsByUser.
func (mr *MockBalanceRepoMockRecorder) FindWithdrawalsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithdrawalsByUser", reflect.TypeOf((*MockBalanceRepo)(nil).FindWithdrawalsByUser), ctx, userID)
}

// GetBalanceByUser mocks base method.
func (m *MockBalanceRepo) GetBalanceByUser(ctx context.Context, userID int) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceByUser", ctx, userID)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceByUser indicates an expected call of GetBalanceByUser.
func (mr *MockBalanceRepoMockRecorder) GetBalanceByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceByUser", reflect.TypeOf((*MockBalanceRepo)(nil).GetBalanceByUser), ctx, userID)
}

// SaveWithdrawal mocks base method.
func (m *MockBalanceRepo) SaveWithdrawal(ctx context.Context, orderNumber string, userID int, amount decimal.Decimal) (*model.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveWithdrawal", ctx, orderNumber, userID, amount)
	ret0, _ := ret[0].(*model.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveWithdrawal indicates an expected call of SaveWithdrawal.
func (mr *MockBalanceRepoMockRecorder) SaveWithdrawal(ctx, orderNumber, userID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveWithdrawal", reflect.TypeOf((*MockBalanceRepo)(nil).SaveWithdrawal), ctx, orderNumber, userID, amount)
}
