// Code generated by MockGen. DO NOT EDIT.
// Source: loyalty-service/internal/service (interfaces: BalanceRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/balance_repository.go -package=mocks . BalanceRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "loyalty-service/internal/model"
	reflect "reflect"

	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockBalanceRepository is a mock of BalanceRepository interface.
type MockBalanceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceRepositoryMockRecorder
	isgomock struct{}
}

// MockBalanceRepositoryMockRecorder is the mock recorder for MockBalanceRepository.
type MockBalanceRepositoryMockRecorder struct {
	mock *MockBalanceRepository
}

// NewMockBalanceRepository creates a new mock instance.
func NewMockBalanceRepository(ctrl *gomock.Controller) *MockBalanceRepository {
	mock := &MockBalanceRepository{ctrl: ctrl}
	mock.recorder = &MockBalanceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceRepository) EXPECT() *MockBalanceRepositoryMockRecorder {
	return m.recorder
}

// FindWithdrawalsByUser mocks base method.
func (m *MockBalanceRepository) FindWithdrawalsByUser(ctx context.Context, userID int) ([]model.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithdrawalsByUser", ctx, userID)
	ret0, _ := ret[0].([]model.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWithdrawalsByUser indicates an expected call of FindWithdrawalsByUser.
func (mr *MockBalanceRepositoryMockRecorder) FindWithdrawalsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithdrawalsByUser", reflect.TypeOf((*MockBalanceRepository)(nil).FindWithdrawalsByUser), ctx, userID)
}

// GetBalanceByUser mocks base method.
func (m *MockBalanceRepository) GetBalanceByUser(ctx context.Context, userID int) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceByUser", ctx, userID)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceByUser indicates an expected call of GetBalanceByUser.
func (mr *MockBalanceRepositoryMockRecorder) GetBalanceByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceByUser", reflect.TypeOf((*MockBalanceRepository)(nil).GetBalanceByUser), ctx, userID)
}

// SaveWithdrawal mocks base method.
func (m *MockBalanceRepository) SaveWithdrawal(ctx context.Context, orderNumber string, userID int, amount decimal.Decimal) (*model.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveWithdrawal", ctx, orderNumber, userID, amount)
	ret0, _ := ret[0].(*model.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveWithdrawal indicates an expected call of SaveWithdrawal.
func (mr *MockBalanceRepositoryMockRecorder) SaveWithdrawal(ctx, orderNumber, userID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveWithdrawal", reflect.TypeOf((*MockBalanceRepository)(nil).SaveWithdrawal), ctx, orderNumber, userID, amount)
}
