// Code generated by MockGen. DO NOT EDIT.
// Source: loyalty-service/internal/service (interfaces: OrderRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/order_repository.go -package=mocks . OrderRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "loyalty-service/internal/model"
	reflect "reflect"

	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// FindOrdersByStatuses mocks base method.
func (m *MockOrderRepository) FindOrdersByStatuses(ctx context.Context, statuses []model.OrderStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FindOrdersByStatuses", ctx, statuses)
}

// FindOrdersByStatuses indicates an expected call of FindOrdersByStatuses.
func (mr *MockOrderRepositoryMockRecorder) FindOrdersByStatuses(ctx, statuses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrdersByStatuses", reflect.TypeOf((*MockOrderRepository)(nil).FindOrdersByStatuses), ctx, statuses)
}

// FindOrdersByUser mocks base method.
func (m *MockOrderRepository) FindOrdersByUser(ctx context.Context, userID int) ([]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrdersByUser", ctx, userID)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrdersByUser indicates an expected call of FindOrdersByUser.
func (mr *MockOrderRepositoryMockRecorder) FindOrdersByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrdersByUser", reflect.TypeOf((*MockOrderRepository)(nil).FindOrdersByUser), ctx, userID)
}

// SaveOrder mocks base method.
func (m *MockOrderRepository) SaveOrder(ctx context.Context, orderNumber string, userID int) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOrder", ctx, orderNumber, userID)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveOrder indicates an expected call of SaveOrder.
func (mr *MockOrderRepositoryMockRecorder) SaveOrder(ctx, orderNumber, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOrder", reflect.TypeOf((*MockOrderRepository)(nil).SaveOrder), ctx, orderNumber, userID)
}

// UpdateOrderStatus mocks base method.
func (m *MockOrderRepository) UpdateOrderStatus(ctx context.Context, orderNumber string, status model.OrderStatus, accrual decimal.Decimal) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, orderNumber, status, accrual)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockOrderRepositoryMockRecorder) UpdateOrderStatus(ctx, orderNumber, status, accrual any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockOrderRepository)(nil).UpdateOrderStatus), ctx, orderNumber, status, accrual)
}
