// Code generated by MockGen. DO NOT EDIT.
// Source: loyalty-service/internal/service (interfaces: OrderRepo)
//
// Generated by this command:
//
//	mockgen -destination=mocks/order_repo.go -package=mocks . OrderRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "loyalty-service/internal/model"
	reflect "reflect"

	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderRepo is a mock of OrderRepo interface.
type MockOrderRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepoMockRecorder
	isgomock struct{}
}

// MockOrderRepoMockRecorder is the mock recorder for MockOrderRepo.
type MockOrderRepoMockRecorder struct {
	mock *MockOrderRepo
}

// NewMockOrderRepo creates a new mock instance.
func NewMockOrderRepo(ctrl *gomock.Controller) *MockOrderRepo {
	mock := &MockOrderRepo{ctrl: ctrl}
	mock.recorder = &MockOrderRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepo) EXPECT() *MockOrderRepoMockRecorder {
	return m.recorder
}

// FindOrdersByStatuses mocks base method.
func (m *MockOrderRepo) FindOrdersByStatuses(ctx context.Context, statuses []model.OrderStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FindOrdersByStatuses", ctx, statuses)
}

// FindOrdersByStatuses indicates an expected call of FindOrdersByStatuses.
func (mr *MockOrderRepoMockRecorder) FindOrdersByStatuses(ctx, statuses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrdersByStatuses", reflect.TypeOf((*MockOrderRepo)(nil).FindOrdersByStatuses), ctx, statuses)
}

// FindOrdersByUser mocks base method.
func (m *MockOrderRepo) FindOrdersByUser(ctx context.Context, userID int) ([]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrdersByUser", ctx, userID)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrdersByUser indicates an expected call of FindOrdersByUser.
func (mr *MockOrderRepoMockRecorder) FindOrdersByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrdersByUser", reflect.TypeOf((*MockOrderRepo)(nil).FindOrdersByUser), ctx, userID)
}

// SaveOrder mocks base method.
func (m *MockOrderRepo) SaveOrder(ctx context.Context, orderNumber string, userID int) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOrder", ctx, orderNumber, userID)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveOrder indicates an expected call of SaveOrder.
func (mr *MockOrderRepoMockRecorder) SaveOrder(ctx, orderNumber, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOrder", reflect.TypeOf((*MockOrderRepo)(nil).SaveOrder), ctx, orderNumber, userID)
}

// UpdateOrderStatus mocks base method.
func (m *MockOrderRepo) UpdateOrderStatus(ctx context.Context, orderNumber string, status model.OrderStatus, accrual decimal.Decimal) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, orderNumber, status, accrual)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockOrderRepoMockRecorder) UpdateOrderStatus(ctx, orderNumber, status, accrual any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockOrderRepo)(nil).UpdateOrderStatus), ctx, orderNumber, status, accrual)
}
