// Code generated by MockGen. DO NOT EDIT.
// Source: loyalty-service/internal/service (interfaces: OrdersRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/order_repository.go -package=mocks . OrdersRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "loyalty-service/internal/model"
	reflect "reflect"

	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockOrdersRepository is a mock of OrdersRepository interface.
type MockOrdersRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrdersRepositoryMockRecorder
	isgomock struct{}
}

// MockOrdersRepositoryMockRecorder is the mock recorder for MockOrdersRepository.
type MockOrdersRepositoryMockRecorder struct {
	mock *MockOrdersRepository
}

// NewMockOrdersRepository creates a new mock instance.
func NewMockOrdersRepository(ctrl *gomock.Controller) *MockOrdersRepository {
	mock := &MockOrdersRepository{ctrl: ctrl}
	mock.recorder = &MockOrdersRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdersRepository) EXPECT() *MockOrdersRepositoryMockRecorder {
	return m.recorder
}

// FindOrdersByStatuses mocks base method.
func (m *MockOrdersRepository) FindOrdersByStatuses(ctx context.Context, statuses []string, limit, offset int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrdersByStatuses", ctx, statuses, limit, offset)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrdersByStatuses indicates an expected call of FindOrdersByStatuses.
func (mr *MockOrdersRepositoryMockRecorder) FindOrdersByStatuses(ctx, statuses, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrdersByStatuses", reflect.TypeOf((*MockOrdersRepository)(nil).FindOrdersByStatuses), ctx, statuses, limit, offset)
}

// FindOrdersByUser mocks base method.
func (m *MockOrdersRepository) FindOrdersByUser(ctx context.Context, userID, limit, offset int) ([]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrdersByUser", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrdersByUser indicates an expected call of FindOrdersByUser.
func (mr *MockOrdersRepositoryMockRecorder) FindOrdersByUser(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrdersByUser", reflect.TypeOf((*MockOrdersRepository)(nil).FindOrdersByUser), ctx, userID, limit, offset)
}

// FindUserIDByOrderNumber mocks base method.
func (m *MockOrdersRepository) FindUserIDByOrderNumber(ctx context.Context, orderNumber string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserIDByOrderNumber", ctx, orderNumber)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserIDByOrderNumber indicates an expected call of FindUserIDByOrderNumber.
func (mr *MockOrdersRepositoryMockRecorder) FindUserIDByOrderNumber(ctx, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserIDByOrderNumber", reflect.TypeOf((*MockOrdersRepository)(nil).FindUserIDByOrderNumber), ctx, orderNumber)
}

// SaveOrder mocks base method.
func (m *MockOrdersRepository) SaveOrder(ctx context.Context, userID int, orderNumber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOrder", ctx, userID, orderNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveOrder indicates an expected call of SaveOrder.
func (mr *MockOrdersRepositoryMockRecorder) SaveOrder(ctx, userID, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOrder", reflect.TypeOf((*MockOrdersRepository)(nil).SaveOrder), ctx, userID, orderNumber)
}

// UpdateOrderInfo mocks base method.
func (m *MockOrdersRepository) UpdateOrderInfo(ctx context.Context, orderNumber string, status model.OrderStatus, accrual decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderInfo", ctx, orderNumber, status, accrual)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderInfo indicates an expected call of UpdateOrderInfo.
func (mr *MockOrdersRepositoryMockRecorder) UpdateOrderInfo(ctx, orderNumber, status, accrual any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderInfo", reflect.TypeOf((*MockOrdersRepository)(nil).UpdateOrderInfo), ctx, orderNumber, status, accrual)
}
