// Code generated by MockGen. DO NOT EDIT.
// Source: loyalty-service/internal/worker/accrual (interfaces: AccrualClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/accrual_client.go -package=mocks . AccrualClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	accrual "loyalty-service/internal/client/accrual"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAccrualClient is a mock of AccrualClient interface.
type MockAccrualClient struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualClientMockRecorder
	isgomock struct{}
}

// MockAccrualClientMockRecorder is the mock recorder for MockAccrualClient.
type MockAccrualClientMockRecorder struct {
	mock *MockAccrualClient
}

// NewMockAccrualClient creates a new mock instance.
func NewMockAccrualClient(ctrl *gomock.Controller) *MockAccrualClient {
	mock := &MockAccrualClient{ctrl: ctrl}
	mock.recorder = &MockAccrualClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualClient) EXPECT() *MockAccrualClientMockRecorder {
	return m.recorder
}

// GetOrderInfo mocks base method.
func (m *MockAccrualClient) GetOrderInfo(ctx context.Context, orderNumber string) (*accrual.OrderInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderInfo", ctx, orderNumber)
	ret0, _ := ret[0].(*accrual.OrderInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderInfo indicates an expected call of GetOrderInfo.
func (mr *MockAccrualClientMockRecorder) GetOrderInfo(ctx, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderInfo", reflect.TypeOf((*MockAccrualClient)(nil).GetOrderInfo), ctx, orderNumber)
}
