// Code generated by MockGen. DO NOT EDIT.
// Source: loyalty-service/internal/worker/accrual (interfaces: OrdersRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/orders_repository.go -package=mocks . OrdersRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "loyalty-service/internal/model"
	reflect "reflect"

	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockOrdersRepository is a mock of OrdersRepository interface.
type MockOrdersRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrdersRepositoryMockRecorder
	isgomock struct{}
}

// MockOrdersRepositoryMockRecorder is the mock recorder for MockOrdersRepository.
type MockOrdersRepositoryMockRecorder struct {
	mock *MockOrdersRepository
}

// NewMockOrdersRepository creates a new mock instance.
func NewMockOrdersRepository(ctrl *gomock.Controller) *MockOrdersRepository {
	mock := &MockOrdersRepository{ctrl: ctrl}
	mock.recorder = &MockOrdersRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdersRepository) EXPECT() *MockOrdersRepositoryMockRecorder {
	return m.recorder
}

// FindOrdersByStatuses mocks base method.
func (m *MockOrdersRepository) FindOrdersByStatuses(ctx context.Context, statuses []string, limit, offset int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrdersByStatuses", ctx, statuses, limit, offset)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrdersByStatuses indicates an expected call of FindOrdersByStatuses.
func (mr *MockOrdersRepositoryMockRecorder) FindOrdersByStatuses(ctx, statuses, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrdersByStatuses", reflect.TypeOf((*MockOrdersRepository)(nil).FindOrdersByStatuses), ctx, statuses, limit, offset)
}

// UpdateOrderInfo mocks base method.
func (m *MockOrdersRepository) UpdateOrderInfo(ctx context.Context, orderNumber string, status model.OrderStatus, accrual decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderInfo", ctx, orderNumber, status, accrual)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderInfo indicates an expected call of UpdateOrderInfo.
func (mr *MockOrdersRepositoryMockRecorder) UpdateOrderInfo(ctx, orderNumber, status, accrual any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderInfo", reflect.TypeOf((*MockOrdersRepository)(nil).UpdateOrderInfo), ctx, orderNumber, status, accrual)
}
